name = "vidhunt-api"
main = "worker.js"
compatibility_date = "2024-03-01"

[[kv_namespaces]]
binding = "CHANNEL_DATA"
id = "f897497753664274b9556fbab3d6dbf1"

# Environment variables (use wrangler secret to set these securely)
[vars]
GOOGLE_DRIVE_FOLDER_ID = "1MsoASuSXq1HkW-tbdh0PjqmeaSxE8DL5"
GOOGLE_CLIENT_ID = "159046785658-07hf5ani7blsafsav0vrl19db7pkamdp.apps.googleusercontent.com"

[env.production]
name = "vidhunt-api"