name = "listup"
main = "worker.js"
compatibility_date = "2024-03-01"

[[kv_namespaces]]
binding = "CHANNEL_DATA"
id = "b6cba85d233f45e294e44b0f49b70eb7"
preview_id = "b6cba85d233f45e294e44b0f49b70eb7"

# Environment variables (use wrangler secret to set these securely)
[vars]
GOOGLE_DRIVE_FOLDER_ID = "1GNWbwAf5F0UoU3_3ZX-xGspKNy4lA90N"
GOOGLE_CLIENT_ID = "196530803280-23q05vfrujb87dcuirfdbdkt9h78srjc.apps.googleusercontent.com"

[env.production]
name = "listup"